### ISSUE TITLE
file size and file hashdigest are not retained during add/subtract commands

### ISSUE THREAD

**Issue by BruceMty** [simsong/hashdb#3]
filesize and file hashdigest information are not transferred to the destination database for any of the database manipulation commands.

**Comment by jjonesu** [comment]
Is add_repository disabled in 1.1.2 for this reason? In main.cpp:

  } else if (command == "add_repository") {
    no_p(); no_m(); no_r(); no_s(); no_A(); no_B(); no_C();
    require_parameter_count(3);

I added this line:
    commands_t::add_repository(hashdb_arg1, hashdb_arg2, hashdb_arg3);
to enable the add_repository functionality, but haven't fully checked the results.

We're using several add_repository runs to create a hdb that is then subtracted from the original hdb to remove specific repositories from an existing hdb, so retention of file size and file digest isn't an issue.

**Comment by BruceMty** [comment]
The add_repository function is not being discontinued.  The repository
name is the third argument, and is not an optional parameter.  That is
why the code does not allow providing it as an optional parameter.

Your use-case clearly shows the need to subtract a specific repository. 
In the next release I'll introduce new command "subtract_repository" to
allow this use-case:

subtract_repository <A.hdb> <B.hdb> <repository name>
add A to B unless repository name matches.

In all database manipulation commands, whenever a hash is added, hashdb
makes sure its corresponding source information including file size and
file digest has been added, too.
